### ISSUE TITLE
ESM build broken in Node.js — extensionless relative imports in `dist/esm/`

### ISSUE THREAD

**Issue by joshjohanning** [tool3/chartscii#152]
## Bug

In a Node.js ESM project (`"type": "module"` in `package.json`), importing chartscii fails at runtime after upgrading to v4.0.0:

```js
import chartscii from 'chartscii';
```

**Error:**
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
'.../node_modules/chartscii/dist/esm/chartscii'
imported from .../node_modules/chartscii/dist/esm/index.js
```

## Root cause

Node resolves the `import` condition from the `exports` field to `dist/esm/index.js`. That file contains:

```js
import Chartscii from './chartscii';
```

Node's ESM resolver **requires explicit file extensions** on relative imports — it does not auto-append `.js`. The file on disk is `dist/esm/chartscii.js`, so resolution fails.

This affects **all relative imports throughout `dist/esm/`**, not just `index.js` — e.g. `./formatters/horizontal`, `./processor/processor`, `./formatters/line`, etc. Fixing only `index.js` would expose the next broken import.

The CJS build works because CommonJS `require()` performs automatic extension resolution.

## Fix

Emit explicit `.js` extensions on all relative imports in the ESM build output. With TypeScript, this means:
- Set `moduleResolution: "NodeNext"` (or `"Bundler"`) in `tsconfig`
- Write source imports with `.js` extensions: `import Chartscii from './chartscii.js'`

TypeScript resolves `.js` imports to `.ts` source files at compile time and emits valid Node ESM.

## Workaround (for consumers until fixed)

```js
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const chartscii = require('chartscii').default;
```

This bypasses the broken ESM entrypoint and loads the working CJS build.

## Environment

- `chartscii`: 4.0.0
- Node.js: v24.15.0
- Project type: ESM (`"type": "module"`)

**Comment by tool3** [comment]
Hey @joshjohanning!  Good to see you here again 😊 Thanks for brining this to my attention.

Please  review https://github.com/tool3/chartscii/pull/153 try it and let me know if that fixes the issue.

Looking forward for your feedback on v4 😊

**Comment by joshjohanning** [comment]
👋  to you too @tool3! Yes the patch works great now w/o the workaround 😁

**Comment by joshjohanning** [comment]
PS: Super excited to play around with the stacked charts in v4! 🙇

**Comment by tool3** [comment]
Awesome! Would love any feedback you have in general on v4 feel free to open an issue or just start a discussion 😊

**Comment by tool3** [comment]
Resolve by v4.0.1 :)

**Comment by joshjohanning** [comment]
Thank you! 🙇
